image: docker:latest

services:
  - docker:dind

stages:
  - prepare
  - test
  - publish
  - deploy

variables:
  NODE_IMAGE: 'biongo/node:20-pnpm'
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_USER: 'biongo'
  DOCKER_REPO: 'hello'
  DOCKER_PASSWORD: '$DOCKER_PASSWORD'
  IMAGE_TAG: '$CI_COMMIT_SHORT_SHA'
  K8S_NAMESPACE: 'biongo-dev-dev'

include:
  - local: '.gitlab/ci/prepare/detect.yaml'
  - local: '.gitlab/ci/prepare/install.yaml'
  - local: '.gitlab/ci/prepare/check.yaml'
  - local: '.gitlab/ci/test/unit.yaml'
  - local: '.gitlab/ci/publish/build_push.yaml'
  - local: '.gitlab/cd/deploy.yaml'
