apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppf
  labels:
    app: ppf
spec:
  replicas: 2 # 至少 2 个 Pod
  selector:
    matchLabels:
      app: ppf
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 同时最多多出来 1 个 Pod
      maxUnavailable: 0 # 升级期间保证总是可用
  template:
    metadata:
      labels:
        app: ppf
    spec:
      containers:
        - name: ppf
          image: biongo/ppf
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
      restartPolicy: Always
