apiVersion: v1
kind: Service
metadata:
  name: ppf-ui-service
  labels:
    app: ppf-ui
spec:
  type: ClusterIP
  selector:
    app: ppf-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
