apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  replicas: 2 # 至少 2 个 Pod
  selector:
    matchLabels:
      app: cms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 同时最多多出来 1 个 Pod
      maxUnavailable: 0 # 升级期间保证总是可用
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: biongo/cms
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
      restartPolicy: Always
